// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ShortenerRepo is an autogenerated mock type for the ShortenerRepo type
type ShortenerRepo struct {
	mock.Mock
}

// GetShortenerByID provides a mock function with given fields: shortenerID
func (_m *ShortenerRepo) GetShortenerByID(shortenerID string) (string, error) {
	ret := _m.Called(shortenerID)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(shortenerID)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(shortenerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
